# docker-compose.yml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn "src.api.main:app" --host 0.0.0.0 --port 8000 --log-level "debug"'
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fishnames
    depends_on:
      - db
  db:
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fishnames

volumes:
  postgres_data: